name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Executa todo dia à meia-noite UTC
  workflow_dispatch:

jobs:
  build:
    name: Generate Snake Animation
    runs-on: ubuntu-latest

    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: Aline-Fernandez
          outputs: |
  dist/github-contribution-grid-snake.svg?palette=https://raw.githubusercontent.com/Aline-Fernandez/commit-snak/main/palette.json
  dist/github-contribution-grid-snake-dark.svg?palette=https://raw.githubusercontent.com/Aline-Fernandez/commit-snak/main/palette.json


      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
